server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: member
          predicates:
            - Path=/member/**
          uri: http://127.0.0.1:8001
        - id: member
          predicates:
            - Path=/business/**
          uri: http://127.0.0.1:8002
      globalcors:
        cors-configurations:
          #针对后端所有接口
          '[/**]':
            # 是否允许携带cookie
            allowCredentials: true
            # 允许携带的头信息
            allowedHeaders: '*'
            # 允许的请求方式
            allowedMethods: '*'
            # 允许请求来源（老版本叫allowedOrigin）
            allowedOriginPatterns: '*'
            # 跨域检测的有效期，会发起一个OPTION请求
            maxAge: 3600


